function formatQuestionBank(workerResults) {
    let md = `# Generative AI for Beginners — Interval Question Bank\n\n`;
    md += `Generated by ${Object.keys(workerResults).length} parallel worker agents covering the first 5 course sections.\n\n`;
    md += `---\n\n`;

    let questionNumber = 1;

    for (const [moduleName, raw] of Object.entries(workerResults)) {
        md += `## Module: ${moduleName}\n\n`;

        let parsed;
        try {
            const cleaned = raw.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
            parsed = JSON.parse(cleaned);
        } catch (_) {
            md += `> Worker returned non-JSON output:\n\n${raw}\n\n---\n\n`;
            continue;
        }

        for (const q of parsed.questions || []) {
            md += `### Q${questionNumber}: ${q.question}\n\n`;
            md += `**Type:** ${q.type}\n\n`;
            md += `**What a good answer covers:**\n`;
            for (const point of q.expected_answer_points || []) {
                md += `- ${point}\n`;
            }
            md += `\n---\n\n`;
            questionNumber++;
        }
    }

    return md;
}

module.exports = { formatQuestionBank };
