// run.js — Phase 2: Multi-Agent Question Generator
//
// 3 workers divide the 5 sections and each produce 2 interval questions per section.
// Orchestrator collects results and writes a single question bank file.
//
// Workers run in parallel — each has its own isolated context window.

require("dotenv").config({ path: require("path").join(__dirname, "../.env") });
const fs = require("fs");
const path = require("path");
const WorkerAgent = require("./worker");

const OUTPUT_DIR = path.join(__dirname, "../outputs");
const OUTPUT_FILE = "multi_agent_output.md";

// 5 sections split across 3 workers
const WORK_PARTITIONS = {
    foundations: [
        {
            name: "00 - Course Setup",
            url: "https://raw.githubusercontent.com/microsoft/generative-ai-for-beginners/main/00-course-setup/README.md",
        },
        {
            name: "01 - Introduction to Generative AI and LLMs",
            url: "https://raw.githubusercontent.com/microsoft/generative-ai-for-beginners/main/01-introduction-to-genai/README.md",
        },
    ],
    selection_and_responsibility: [
        {
            name: "02 - Exploring and Comparing Different LLMs",
            url: "https://raw.githubusercontent.com/microsoft/generative-ai-for-beginners/main/02-exploring-and-comparing-different-llms/README.md",
        },
        {
            name: "03 - Using Generative AI Responsibly",
            url: "https://raw.githubusercontent.com/microsoft/generative-ai-for-beginners/main/03-using-generative-ai-responsibly/README.md",
        },
    ],
    prompting: [
        {
            name: "04 - Prompt Engineering Fundamentals",
            url: "https://raw.githubusercontent.com/microsoft/generative-ai-for-beginners/main/04-prompt-engineering-fundamentals/README.md",
        },
    ],
};

async function runWorker(name, sections) {
    const worker = new WorkerAgent(name, sections);
    const result = await worker.run();
    console.log(`  ✓ Worker '${name}' finished`);
    return { name, result };
}

function formatQuestionBank(workerResults) {
    let md = `# Generative AI for Beginners — Interval Question Bank\n\n`;
    md += `Generated by ${Object.keys(workerResults).length} parallel worker agents covering the first 5 course sections.\n\n`;
    md += `---\n\n`;

    let questionNumber = 1;

    for (const [moduleName, raw] of Object.entries(workerResults)) {
        md += `## Module: ${moduleName}\n\n`;

        let parsed;
        try {
            const cleaned = raw.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
            parsed = JSON.parse(cleaned);
        } catch (_) {
            md += `> Worker returned non-JSON output:\n\n${raw}\n\n---\n\n`;
            continue;
        }

        for (const q of parsed.questions || []) {
            md += `### Q${questionNumber}: ${q.question}\n\n`;
            md += `**Type:** ${q.type}\n\n`;
            md += `**What a good answer covers:**\n`;
            for (const point of q.expected_answer_points || []) {
                md += `- ${point}\n`;
            }
            md += `\n---\n\n`;
            questionNumber++;
        }
    }

    return md;
}

async function main() {
    console.log("=".repeat(50));
    console.log("PHASE 2: MULTI-AGENT QUESTION GENERATOR");
    console.log("=".repeat(50));
    console.log(`\nSpawning 3 workers in parallel across 5 sections...\n`);

    const wallStart = Date.now();

    const workerOutputs = await Promise.all(
        Object.entries(WORK_PARTITIONS).map(([name, sections]) => runWorker(name, sections))
    );

    const workerTime = ((Date.now() - wallStart) / 1000).toFixed(1);
    console.log(`\nAll workers done in ${workerTime}s`);
    console.log("Orchestrator formatting question bank...\n");

    const workerResults = Object.fromEntries(
        workerOutputs.map(({ name, result }) => [name, result])
    );

    const questionBank = formatQuestionBank(workerResults);

    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    const outputPath = path.join(OUTPUT_DIR, OUTPUT_FILE);
    fs.writeFileSync(outputPath, questionBank, "utf-8");

    const totalTime = ((Date.now() - wallStart) / 1000).toFixed(1);
    const totalSections = Object.values(WORK_PARTITIONS).flat().length;
    const totalQuestions = totalSections * 2;

    console.log(`✓ Done. Output: outputs/${OUTPUT_FILE}`);
    console.log(`  Workers: ${workerTime}s | Total: ${totalTime}s`);
    console.log(`  Sections covered: ${totalSections} | Questions generated: ${totalQuestions}`);
}

main().catch(console.error);
